owner: Samuel-Martineau
repo: Smartineau.me-Status

sites:
  - name: Site web personnel
    url: https://smartineau.me
    icon: https://smartineau.me/favicon.png
  - name: Meli
    url: https://meli.smartineau.me
  - name: Fichiers
    url: https://fichiers.smartineau.me
  - name: Simulateur d'évolution - Expo-sciences
    url: https://simulateur-evolution.expo-sciences.smartineau.me/
  - name: MondiumCJE
    url: https://mondium.smartineau.me/paiement
  - name: Minecraft Vanilla (Privé)
    url: $VANILLA_MC_DOMAIN
    icon: https://raw.githubusercontent.com/Samuel-Martineau/Smartineau.me-Status/master/assets/minecraft.png
    check: tcp-ping
    port: 25565

status-website:
  cname: status.smartineau.me
  theme: ocean
  logoUrl: https://raw.githubusercontent.com/Samuel-Martineau/Smartineau.me-Status/master/assets/upptime-icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

user-agent: Smartineaume-Satus
