owner: Samuel-Martineau
repo: Smartineau.me-Etat

sites:
  - name: Site web personnel
    url: https://smartineau.me
    icon: https://smartineau.me/favicon.png
  - name: Meli
    url: https://meli.smartineau.me
  - name: Minecraft Vanilla (Privé)
    url: $VANILLA_MC_DOMAIN
    icon: https://raw.githubusercontent.com/Samuel-Martineau/Smartineau.me-Etat/master/assets/minecraft.png
    check: tcp-ping
    port: 25565

status-website:
  cname: état.smartineau.me
  theme: ocean
  logoUrl: https://raw.githubusercontent.com/Samuel-Martineau/Smartineau.me-Etat/master/assets/upptime-icon.svg
  name: Upptime
  navbar:
    - title: État
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  activeIncidents: Incidents en cours
  allSystemsOperational: Aucun problème détecté
  incidentReport: "Rapport de l'incident #$NUMBER →"
  activeIncidentSummary: Ouvert à $DATE avec $POSTS publication(s)
  incidentTitle: "Détails de l'incident #$NUMBER"
  incidentDetails: Détails de l'incident
  incidentFixed: Réglé
  incidentOngoing: En cours
  incidentOpenedAt: Ouvert à
  incidentClosedAt: Fermé à
  incidentSubscribe: Suivre les mises à jour
  incidentViewOnGitHub: Voir sur GitHub
  incidentCommentSummary: Publié à $DATE par $AUTHOR
  incidentBack: ← Tous les incidents
  pastIncidents: Incidents passés
  pastIncidentsResolved: Réglé en $MINUTES minute(s) avec $POSTS publication(s)
  liveStatus: État en direct
  overallUptime: "Temps de fonctionnement total: $UPTIME"
  overallUptimeTitle: Temps de fonctionnement total
  averageResponseTime: "Temps de réponse moyen: $TIMEms"
  averageResponseTimeTitle: Réponse moyenne
  sevelDayResponseTime: Temps de réponse sur 7 jours
  responseTimeMs: Temps de réponse (ms)
  up: 🟩 Ouvert
  down: 🟥 En panne
  degraded: 🟨 Endommagé
  ms: ms
  loading: Chargement
  navGitHub: GitHub
  footer: Ce site est généré par [Upptime](https://upptime.js.org)
  errorTitle: Une erreur s'est produite
  errorIntro: Une erreur s'est produite lors de l'accès aux dernières données
  errorText: Réessayer dans quelques instants
  errorHome: Aller à l'accueil
  pastScheduledMaintenance: Entretiens planifiés passés
  scheduledMaintenance: Entretiens planifiés
  scheduledMaintenanceSummaryStarted: Débuté à $DATE pour $DURATION minute(s)
  scheduledMaintenanceSummaryStarts: Débutera à $DATE pour $DURATION minute(s)
  startedAt: Débuté à
  startsAt: Débutera à
  duration: Durée
  durationMin: $DURATION minute(s)
  incidentCompleted: Complété
  incidentScheduled: Planifié
  url: URL
  status: État
  history: Historique
  responseTime: Temps de réponse
  uptime: Temps de fonctionnement
  responseTimeGraphAlt: Graphique du temps de réponse
  responseTimeDay: Temps de réponse sur 24h
  responseTimeWeek: Temps de réponse sur 7j
  responseTimeMonth: Temps de réponse sur 30j
  responseTimeYear: Temps de réponse sur 1 an
  uptimeDay: Temps de fonctionnement sur 24h
  uptimeWeek: Temps de fonctionnement sur 7j
  uptimeMonth: Temps de fonctionnement sur 30j
  uptimeYear: Temps de fonctionnement sur 1 an
  liveStatusHtmlComment: "<!--live status-->"
  degradedPerformance: "🟨 Performance dégradée"
  completeOutage: "🟥 Panne complète"
  partialOutage: "🟧 Panne partielle"
